version: '3'

services:
    nginx:
        image: nginx:1.21.0
        container_name: "xfrm_nginx"
        ports:
            - "3000:80"
        depends_on:
            - "php"
        volumes:
            - "./docker/nginx.conf:/etc/nginx/nginx.conf"
            - "./docker/www/:/usr/share/nginx/html/xfrm/"
            - "./docker/logs/:/var/log/nginx/"

    php:
        container_name: "xfrm_php"
        build:
            context: "docker/php"
            dockerfile: "build"
        expose:
            - "9000"
        volumes: 
            - "./docker/www/:/var/www/html/xfrm/"
